name: Lint

on:
  push:
  pull_request:

jobs:
  web-ext-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: web-ext lint
        run: npx --yes web-ext lint --source-dir .
